version: "3"
services:
  mongodb:
    image: mongo:6.0
    container_name: dca_db
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/entrypoint:/docker-entrypoint-initdb.d/:ro
    ports:
      - "${DB_PORT}:27017"
    env_file:
      - .env
    hostname: "${DB_HOST}"

  backend:
    container_name: dca_backend
    build: backend
    volumes:
      - ./backend:/app
    ports:
      - "${BACKEND_PORT}:5000"
    env_file:
      - .env
    depends_on:
      - mongodb

  frontend:
    container_name: dca_frontend
    build: frontend
    volumes:
      - "./frontend/src:/frontend/src"
      - "./frontend/dist:/frontend/dist"
    ports:
      - "${FRONTEND_PORT}:5173"
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    env_file:
      - .env
    depends_on:
      - backend
