version: "3"
services:
  mongodb:
    image: mongo:6.0
    container_name: dca_db
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/entrypoint:/docker-entrypoint-initdb.d/:ro
    ports:
      - "${DB_PORT}:27017"
    env_file:
      - .env
    hostname: "${DB_HOST}"

  backend:
    container_name: dca_backend
    build:
      context: ./backend/
      dockerfile: Dockerfile.prod
    volumes:
      - ./backend:/app
      - ./certbot/conf/live/:/app/certs/:ro
    ports:
      - "${BACKEND_PORT}:80"
    env_file:
      - .env
    depends_on:
      - mongodb

  nginx:
    container_name: dca_nginx
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/dist/:/var/www/
      - ./nginx/log/:/var/log/nginx/
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - ${FRONTEND_PORT}:80
      - ${FRONTEND_PORT_SSL}:443
    env_file:
      - .env

  certbot:
    container_name: dca_certbot
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - ./certbot/log/letsencrypt/:/var/log/letsencrypt/:rw
