version: "3"
services:
  backend:
    container_name: dca_backend
    build: backend
    volumes:
      - ./backend:/app
    ports:
      - "${BACKEND_PORT}:5000"
    env_file:
      - .env

  frontend:
    container_name: dca_frontend
    build: frontend
    volumes:
      - "./frontend/src:/frontend/src"
    ports:
      - "${FRONTEND_PORT}:5173"
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    env_file:
      - .env
