FROM python:3.10

WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY . .

CMD gunicorn --certfile ./certs/localhost/fullchain.pem --keyfile ./certs/localhost/privkey.pem -b :80 app:app
